### ISSUE TITLE
createJsModules in ReactPackage is deprecated

### ISSUE THREAD

**Issue by arindam89** [wscodelabs/react-native-call-log#11]
Hello Devs,

Our build is failing after using this plugin, due to a breaking change here,

https://github.com/realm/realm-js/issues/1176

Can you udpate the CallLogPackage with either removing the method or removing the @Override comment.

**Comment by piyushcoader** [comment]
@aayushcoder can we update on this

**Comment by aayushcoder** [comment]
This issue was fixed on same day. We need to close this issue

**Comment by aayushcoder** [comment]
Since this issue is already fixed i'm closing it
