### ISSUE TITLE
CallLogs undefined

### ISSUE THREAD

**Issue by jefflivid55** [wscodelabs/react-native-call-log#12]
I am having trouble using this package.

If I clone the repo and run npm install in the Example directory, I get 
`npm ERR! Cannot convert undefined or null to object`

When I try and use the component in my project, I include
`import CallLogs from 'react-native-call-log';`
but CallLogs is undefined in code below that statement

**Comment by piyushcoader** [comment]
i am not able to reproduce same error can you tell which version are you using?

**Comment by aayushcoder** [comment]
There was slight mistake in naming package name in android folder and we have already fixed that.
