### ISSUE TITLE
cannot run the app after linking this package

### ISSUE THREAD

**Issue by Veronica1026** [wscodelabs/react-native-call-log#13]
Hi, I am new to RN android app development, and there is one issue I cannot pass through. 
Before installing this package my app works fine in android emulator, after I installed the package using npm, the app still runs fine, but then after I type in react-native link, my app cannot run in android emulator, saying that "FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html".
Then I went back, start all over and tried to link manually, after editing "android/settings.gradle", my app could still run in android emulator, but after I edit the "android/app/build.gradle" file, the same error came again and I cannot run my app in emulator anymore.
But when I was installing other libraries and trying to link, things went well, so I don't quite understand
what happened here... 
could you kindly look at this issue?

**Comment by Veronica1026** [comment]
ohh now it went 


* What went wrong:
Execution failed for task ':react-native-call-log:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by aayushcoder** [comment]
Sorry for the late response @Veronica1026  .. Did you fixed this issue or it's still there ??

**Comment by aayushcoder** [comment]
If your issue is not fixed yet then install package with ` npm install --save https://github.com/wscodelabs/react-native-call-log`

**Comment by Veronica1026** [comment]
issue fixed! Thank you so much!
