### ISSUE TITLE
native module contactsmanager tried to override contactsmanager for module name contact

### ISSUE THREAD

**Issue by yusuf987** [wscodelabs/react-native-call-log#18]
project info 
"react-native": "0.49.3",
    "react-native-call-log": "^2.1.1",

I am trieng to read call logs but i am not able to build the project saying bellow error 

![image](https://user-images.githubusercontent.com/24749530/57008180-f1e0ea80-6c0b-11e9-8e76-37b76597dcd0.png)

can somebody help me

**Comment by aathapa** [comment]
Not sure the actual cause of this issue. Check additional contact packages installed or may be upgrading to latest react native version could help.
