### ISSUE TITLE
Data returned is questionable?

### ISSUE THREAD

**Issue by peterchibunna** [wscodelabs/react-native-call-log#6]
Sorry about the title but on my android phone, I got a listing with a missed call that has a duration of 30 seconds. Also some call types are neither missed, dialled nor received.

**Comment by piyushcoader** [comment]
hmm well we are just fetching logs  with call log android library not sure why is that happening.  :)

**Comment by peterchibunna** [comment]
Or it could still be the data was altered after I passed it through as an immutable list.I will investigate and report back.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: piyush thapaSent: Wednesday, 7 June 2017 8:36 AMTo: wscodelabs/react-native-call-logReply To: wscodelabs/react-native-call-logCc: peterchibunna; AuthorSubject: Re: [wscodelabs/react-native-call-log] Data returned is questionable? (#6)hmm well we are just fetching logs  with call log android library not sure why is that happening.  :)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wscodelabs/react-native-call-log","title":"wscodelabs/react-native-call-log","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wscodelabs/react-native-call-log"}},"updates":{"snippets":[{"icon":"PERSON","message":"@piyushcoader in #6: hmm well we are just fetching logs  with call log android library not sure why is that happening.  :) "}],"action":{"name":"View Issue","url":"https://github.com/wscodelabs/react-native-call-log/issues/6#issuecomment-306713503"}}}

**Comment by piyushcoader** [comment]
closing for now

**Comment by peterchibunna** [comment]
I investigated this: logged the raw data to the console and got the same result: A missed call with 30 seconds duration.

**Comment by peterchibunna** [comment]
I discovered there are more than the three types of call you return from your lookup.
Calls can be either `BLOCKED_TYPE`, `ANSWERED_EXTERNALLY_TYPE`, `INCOMING_TYPE`, `MISSED_TYPE`, `OUTGOING_TYPE`, `REJECTED_TYPE`, `VOICEMAIL_TYPE`.

The `TYPE` defined only the three possible values (which is what you returned).
This issue above would be absent if we only returned the type from the `callType` variable that you declared in your code https://github.com/wscodelabs/react-native-call-log/blob/master/android/src/main/java/com/wscodelabs/callLogs/CallLogModule.java#L47

**Comment by mikehardy** [comment]
I'm on the late show here but the module supports a minSdkVersion of 16, and the types you mention are for higher SdkVersions.

@peterchibunna I think the appropriate question for people that want all the information possible, would you be willing to accept a PR that has SDK version detection and adds support for the available information for higher API levels?
